export const Symbols = {
    CERTIFICATE_AUTHORITY_CONTROLLER: Symbol.for('CERTIFICATE_AUTHORITY_CONTROLLER'),
    CERTIFICATE_AUTHORITY_VIEW: Symbol.for('CERTIFICATE_AUTHORITY_VIEW'),
    CERTIFICATE_AUTHORITY_SERVICE: Symbol.for('CERTIFICATE_AUTHORITY_SERVICE'),
    CERTIFICATE_AUTHORITY_REPOSITORY: Symbol.for('CERTIFICATE_AUTHORITY_REPOSITORY'),

    LEVEL_UP_DRIVER: Symbol.for('LEVEL_UP_DRIVER'),
}