export const Symbols = {
    CERTIFICATE_AUTHORITY_CONTROLLER: Symbol.for('CERTIFICATE_AUTHORITY_CONTROLLER'),
    CERTIFICATE_AUTHORITY_VIEW: Symbol.for('CERTIFICATE_AUTHORITY_VIEW'),
    CERTIFICATE_AUTHORITY_SERVICE: Symbol.for('CERTIFICATE_AUTHORITY_SERVICE'),
    CERTIFICATE_AUTHORITY_REPOSITORY: Symbol.for('CERTIFICATE_AUTHORITY_REPOSITORY'),

    HYPERLEDGER_WALLET: Symbol.for('HYPERLEDGER_WALLET'),

    USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),
    USER_SERVICE: Symbol.for('USER_SERVICE'),

    LEVEL_UP_DRIVER: Symbol.for('LEVEL_UP_DRIVER'),

    HYPERLEDGER_CA_CLIENT_BUILDER: Symbol.for('HYPERLEDGER_CA_CLIENT_BUILDER'),

    PASSWORD_HASHER: Symbol.for('PASSWORD_HASHER'),

    CLIENT_CONFIG_REPOSITORY: Symbol.for('CLIENT_CONFIG_REPOSITORY'),
    CLIENT_CONFIG_CONTROLLER: Symbol.for('CLIENT_CONFIG_CONTROLLER'),
    CLIENT_CONFIG_VIEW: Symbol.for('CLIENT_CONFIG_VIEW'),
}