export const Channels = {
    ROUTE: 'route',
    ADD_CERTIFICATE_AUTHORITY: 'ADD_CERTIFICATE_AUTHORITY',
    GET_CERTIFICATE_AUTHORITY: 'GET_CERTIFICATE_AUTHORITY',

    SET_SELECTED_CERTIFICATE_AUTHORITY: 'SET_SELECTED_CERTIFICATE_AUTHORITY',
    GET_SELECTED_CERTIFICATE_AUTHORITY: 'GET_SELECTED_CERTIFICATE_AUTHORITY',

    SET_CLIENT_CONFIG: 'SET_CLIENT_CONFIG',
    GET_CLIENT_CONFIG: 'GET_CLIENT_CONFIG',
}